final List<Map<String, dynamic>> foodItems = [
  // ===== FOOD =====
  {
    'title': 'Hamburger',
    'subtitle': 'Bánh mì kẹp thịt',
    'rating': 4.8,
    'image': 'images/products/food1.jpg',
    'description':
        'Hamburger thơm ngon với thịt bò mềm, rau tươi và sốt đặc biệt.',
    'deliveryTime': '20 phút',
    'price': 30000.0,
    'category': 'food',
  },
  {
    'title': 'Gà rán',
    'subtitle': 'Gà giòn truyền thống',
    'rating': 4.7,
    'image': 'images/products/food2.jpg',
    'description': 'Gà rán giòn rụm bên ngoài, mềm ngọt bên trong, đậm vị.',
    'deliveryTime': '25 phút',
    'price': 35000.0,
    'category': 'food',
  },
  {
    'title': 'Gà nướng sốt tiêu',
    'subtitle': 'Gà nướng đậm đà',
    'rating': 4.9,
    'image': 'images/products/food3.jpg',
    'description': 'Gà nướng thơm lừng, phủ sốt tiêu cay nhẹ, rất hấp dẫn.',
    'deliveryTime': '30 phút',
    'price': 45000.0,
    'category': 'food',
  },
  {
    'title': 'Khoai tây chiên',
    'subtitle': 'Giòn tan hấp dẫn',
    'rating': 4.6,
    'image': 'images/products/food4.jpg',
    'description': 'Khoai tây chiên vàng giòn, ăn kèm tương cà cực ngon.',
    'deliveryTime': '15 phút',
    'price': 20000.0,
    'category': 'food',
  },
  {
    'title': 'Sandwich',
    'subtitle': 'Bánh mì kẹp nhẹ',
    'rating': 4.5,
    'image': 'images/products/food5.jpg',
    'description': 'Sandwich tiện lợi với rau, thịt và sốt béo nhẹ.',
    'deliveryTime': '15 phút',
    'price': 25000.0,
    'category': 'food',
  },
  {
    'title': 'Salad',
    'subtitle': 'Rau trộn tươi mát',
    'rating': 4.6,
    'image': 'images/products/food6.jpg',
    'description': 'Salad rau tươi kết hợp sốt nhẹ, tốt cho sức khỏe.',
    'deliveryTime': '10 phút',
    'price': 22000.0,
    'category': 'food',
  },

  // ===== COMBOS =====
  {
    'title': 'Combo 1',
    'subtitle': 'Hamburger + Khoai tây',
    'rating': 4.8,
    'image': 'images/products/combo1.jpg',
    'description': 'Combo tiết kiệm gồm 1 hamburger và 1 khoai tây chiên.',
    'deliveryTime': '25 phút',
    'price': 45000.0,
    'category': 'combos',
  },
  {
    'title': 'Combo 2',
    'subtitle': '3 Hamburger + Khoai tây',
    'rating': 4.9,
    'image': 'images/products/combo2.jpg',
    'description': 'Combo dành cho nhóm: 3 hamburger và 1 phần khoai tây.',
    'deliveryTime': '30 phút',
    'price': 80000.0,
    'category': 'combos',
  },
  {
    'title': 'Combo 3',
    'subtitle': '3 Hamburger + Khoai + Nước',
    'rating': 5.0,
    'image': 'images/products/combo3.jpg',
    'description': 'Combo đầy đủ gồm 3 hamburger, khoai tây và 1 nước uống.',
    'deliveryTime': '35 phút',
    'price': 95000.0,
    'category': 'combos',
  },

  // ===== DRINK =====
  {
    'title': 'Cam ép',
    'subtitle': 'Nước cam tươi',
    'rating': 4.7,
    'image': 'images/products/drink1.jpg',
    'description': 'Nước cam ép tươi mát, giàu vitamin C.',
    'deliveryTime': '10 phút',
    'price': 15000.0,
    'category': 'drink',
  },
  {
    'title': 'Trà chanh',
    'subtitle': 'Thanh mát giải nhiệt',
    'rating': 4.6,
    'image': 'images/products/drink2.jpg',
    'description': 'Trà chanh mát lạnh, vị chua ngọt dễ uống.',
    'deliveryTime': '10 phút',
    'price': 12000.0,
    'category': 'drink',
  },
  {
    'title': 'Fanta',
    'subtitle': 'Nước ngọt có gas',
    'rating': 4.5,
    'image': 'images/products/drink3.jpg',
    'description': 'Fanta mát lạnh, vị cam sảng khoái.',
    'deliveryTime': '5 phút',
    'price': 10000.0,
    'category': 'drink',
  },
  {
    'title': 'Coca Cola',
    'subtitle': 'Nước ngọt',
    'rating': 4.8,
    'image': 'images/products/drink4.jpg',
    'description': 'Coca Cola mát lạnh, giải khát tức thì.',
    'deliveryTime': '5 phút',
    'price': 10000.0,
    'category': 'drink',
  },
];
